In [1]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.81...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 59950}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:33.297062,NaN
1,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.782025,NaN
2,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.872072,NaN
3,GET,/robots.txt,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38286}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.891330,NaN
4,GET,/sitemap.xml,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38288}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.893769,NaN

In [2]:
uuids = df["uuid"]

uuids_matrix = []
tmp = []

for i, x in enumerate(uuids):
  if i % 10 == 0 and i != 0:
    uuids_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  uuids_matrix.append(tmp)

uuids_matrix

[['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9'],
 ['50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',
  '50d7b1f4-6ef6-4338-b372-dbd50f852dd9',

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(uuids_matrix).transform(uuids_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,005cf2da-84df-4b45-89b0-585ae435d135,1046f5a2-4d72-429f-bf49-3457f36b8617,2cb5d888-dac2-4cb2-bd3e-83aafb3191cb,50d7b1f4-6ef6-4338-b372-dbd50f852dd9,5e9acef4-3e24-4748-9f87-e0e287d454fc,dbe7c5cd-d40d-44ba-8a9e-f771a57194b4,e0610efa-8d57-4dec-a165-ea86d0119166,f8a29572-7165-47e0-bbe9-fc023ffa1951
0,False,False,False,True,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...
1141,False,False,False,False,False,False,True,False
1142,False,False,False,False,False,False,True,False
1143,False,False,False,False,False,False,True,False
1144,False,False,False,False,False,False,True,False
1145,False,False,False,False,False,False,True,False

In [11]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.00001, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

     support                                           itemsets
0   0.461606             (50d7b1f4-6ef6-4338-b372-dbd50f852dd9)
1   0.086387             (1046f5a2-4d72-429f-bf49-3457f36b8617)
2   0.039267             (005cf2da-84df-4b45-89b0-585ae435d135)
3   0.149215             (5e9acef4-3e24-4748-9f87-e0e287d454fc)
4   0.142234             (dbe7c5cd-d40d-44ba-8a9e-f771a57194b4)
5   0.039267             (f8a29572-7165-47e0-bbe9-fc023ffa1951)
6   0.031414             (2cb5d888-dac2-4cb2-bd3e-83aafb3191cb)
7   0.056719             (e0610efa-8d57-4dec-a165-ea86d0119166)
8   0.000873  (50d7b1f4-6ef6-4338-b372-dbd50f852dd9, 1046f5a...
9   0.000873  (005cf2da-84df-4b45-89b0-585ae435d135, 1046f5a...
10  0.000873  (005cf2da-84df-4b45-89b0-585ae435d135, 5e9acef...
11  0.000873  (dbe7c5cd-d40d-44ba-8a9e-f771a57194b4, 5e9acef...
12  0.000873  (dbe7c5cd-d40d-44ba-8a9e-f771a57194b4, f8a2957...
13  0.000873  (f8a29572-7165-47e0-bbe9-fc023ffa1951, 2cb5d88...
14  0.000873  (e0610efa-8d57-4dec-a165-ea86d0119166, 2cb5d88...

In [12]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [13]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_uuids (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            UUID            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [14]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_uuids (ID, SUPPORT, UUID)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully