In [1]:
import pandas as pd

df = pd.read_json("../../datas/vps/tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.68...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '172.18.0.1', 'port': 53212}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:30:36.539037,NaN
1,GET,/,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': '7ee68b0c-9f55-47e5-b872-078d30b...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.702421,NaN
2,GET,/stylesheets/jquery/jquery-ui-1.11.0.css?15286...,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30702}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:01.860896,NaN
3,GET,/stylesheets/application.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 30709}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.008505,NaN
4,GET,/stylesheets/responsive.css?1528612569,"{'host': '202.10.35.215', 'connection': 'keep-...",64644ea7-b358-4208-9b28-e5aaad5e00de,"{'ip': '180.248.32.210', 'port': 8026}",200,{'sess_uuid': 'c3f38f1d-a1be-477a-8692-9369ce7...,"{'version': '0.6.0', 'response': {'message': {...",2025-06-14 07:31:02.020142,NaN

In [2]:
sess_uuids_matrix = []
tmp = []
sess_uuids_uuids = {
  # "{sess_uuid}": []
}
uuids = []

for _, row in df.iterrows():
  uuid = row["uuid"]
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")

  if uuid in uuids:
    sess_uuids_uuids[uuid].append(sess_uuid)
  else:
    sess_uuids_uuids[uuid] = [sess_uuid]
    uuids.append(uuid)

sess_uuids_matrix = list(sess_uuids_uuids.values())
# for paths in sess_uuids_uuids.values():
#   sess_uuids_matrix.append(paths)

sess_uuids_uuids
# sess_uuids_matrix
# print(len(sess_uuids_matrix), len(sess_uuids_uuids.keys()))

{'64644ea7-b358-4208-9b28-e5aaad5e00de': ['806c8d58-b04f-4634-b107-34877af9d1d0',
  '7ee68b0c-9f55-47e5-b872-078d30b9116b',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'c3f38f1d-a1be-477a-8692-9369ce7d2c44',
  'f278a7c1-0785-48d7-bf05-539b1f48cc0c',
  '35356d10-0d1c-47ab-b018-36f62dd2a08f',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '1e975ea3-2f2c-4183-a4ca-7637ddbe1eec',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '7c28e45f-7aaa-42fa-b44d-0216a25150ab',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '47685c7c-17cb-4303-8a1e-5e99a9e1f9bd',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  '09e54ba6-8322-4a86-afa8-a01dc89cb59b',
  'fd70efc6-4bea-4488-9b48-259dedb17253',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '98ea628e-45bf-4a62-a0ee-3fab57dbf91d',
  '832ea6af-7ac1-4971-b205-2028efaef538',
  'a32ff6ba-c480-4519-b91e-539517820571',
  '5a39f903-3016-4ecc-990e-e20e8813115d',
  'f98db070-b1c2-4f1e-b019-c13361eeef96'],
 '648c8c37-3275-4dac-9b6a-a44f4796d492': ['8de81429-7607-4d4f-b31c-5e03ff10e2bd',
  '997a2bbc-7e8a-4088-9fb5-05809cdcaf81',
  'f7358105-0eb0-474a-ba3e-6266aca8f90a',
  '623bcb95-5794-42ea-86e6-b1af1a13158c',
  'bbed53f4-35ef-4722-b8df-269a46a691f1',
  'bbed53f4-35ef-4722-b8df-269a46a691f1',
  'bbed53f4-35ef-4722-b8df-269a46a691f1',
  'bbed53f4-35ef-4722-b8df-269a46a691f1',
  '76b1da02-e6c1-4826-b881-a504aefb8f0b',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  '3d120c94-fd09-4619-adcb-715466a1b85f',
  'c9f54414-6d3d-4ab0-84d9-b17a5bc56abe',
  '67ad7734-1a0d-44c4-91fb-f5a95e0cb51f',
  'f7358105-0eb0-474a-ba3e-6266aca8f90a',
  '4021c006-9db4-4278-af06-808ead00ba8f',
  '28e88c97-5ccb-4526-8113-1d65eb3aa43b',
  '28e88c97-5ccb-4526-8113-1d65eb3aa43b',
  'df46768d-6cf6-4b4e-bc82-7cff4ca4a9c1'],
 '279d8e0f-3391-4a45-86f2-31ac81bab393': ['e6dc69dd-97c6-4a9d-a842-8a1802e8e0c5',
  '252b722b-5181-4089-a148-0e6c2eedee0d',
  '5a619609-691d-485b-ba0c-4d7ce6d9e18a',
  'f629a009-4764-4dcf-9121-953912923945',
  'cc4fde00-f118-490f-b158-2eab31ebdd6c',
  '1d20892e-df9a-4816-949f-6416fa32a10a',
  '10760847-7b34-4af7-b53e-1dc0562d21c0',
  '356a10a8-c46b-4c4f-b990-5a87e9626ac2',
  '5a619609-691d-485b-ba0c-4d7ce6d9e18a',
  '9ac9975c-b405-45ff-8c33-814145f20dfd',
  'd0f4dd71-e8c1-4e83-b0ae-0a578031fdb5',
  '1face405-0fa0-40f4-acc5-33f957af9033',
  '8d7db90d-79e6-4029-98f8-324c3d9a3ebb',
  '22f29eb6-221d-4870-8b83-fd04e7d5c30d',
  'ac8bf79c-726f-4aa0-8f12-61b3df10efe8',
  '7738d8a9-292a-4497-904a-7651efcd8f99'],
 '663d806d-8a95-4357-8ae6-25203008ad43': ['a0c8a814-cfc0-4668-bb7d-9c73356c8fbe',
  'c5b8cd87-50cd-4d14-93aa-b3389af9efe1',
  '1df72535-5045-4145-a395-90c20d2c7c11',
  '0ed39147-fed9-4179-82c4-4ff84f92531f',
  '047aa8f9-0d61-433b-8f59-f5f6f8daf6c3',
  'c5dd7888-775b-47a9-a28c-f32584abf216',
  '375ebac4-4589-42e5-be80-2a9a53f64a79',
  'a0c8a814-cfc0-4668-bb7d-9c73356c8fbe',
  '90fb3a1d-d449-409d-a2b4-f32e6ee3ebd5',
  '90fb3a1d-d449-409d-a2b4-f32e6ee3ebd5',
  '1500fa23-b233-4ab6-9e42-9506f8d9a8f5',
  'a876e6c1-6364-4a9a-84e4-41c948ea098a'],
 '383832a0-74fa-4be9-a2d1-a856c661f207': ['b4580408-1ae0-4a35-967f-8b76025da5f4',
  'fdfea6b2-7629-4525-b94e-994d0e1b4c02',
  'a1f02805-3232-478b-afc7-933f606700fe',
  '8e4e6af6-8732-476a-b29f-d0a0d0fd7cf1',
  'fdfea6b2-7629-4525-b94e-994d0e1b4c02',
  '8d8e54c9-574e-4ae1-8a1f-24cd557d6efc',
  'ed57daaa-8e5a-4748-91bf-bf12f95605c3',
  '4a1d05e4-7d48-4e60-a4b6-d68543ee6f4e'],
 'c35ab0ff-a8af-47ea-8be3-c5e3f6fe6146': ['1af6395b-05c0-49e9-a63d-31774b8cc443',
  'c8c7da1a-0809-4459-b070-f860ed4b6e90',
  '5e63f4e3-72a3-4606-a7d7-607202abd111',
  'b44b53e8-b996-44cd-9701-0b1acf642b74',
  '886bacbd-0835-41af-97fc-4077f5410d07',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  'b72a5770-2033-454c-b116-3a58b0a0fb70',
  '5e63f4e3-72a3-4606-a7d7-607202abd111'],
 '08fa80ad-d3ab-42ca-9bda-ecb7b3f0f316': ['4cc3e677-ae7f-4272-ac1e-e80e4a528a99',
  '788a58e6-faf9-4329-9c7e-0d6d3b6bb778',
  'a095275f-688e-4743-9df6-a56cc877f543',
  'f8d5daeb-62a8-4332-9b88-3da8f0052d77',
  '17ebd84f-9971-4643-8a31-7cc8cd1b82b6',
  '7aea6c15-f917-460b-ad42-c7226e11fb0f',
  '7aea6c15-f917-460b-ad42-c7226e11fb0f',
  '8fd1aabe-0fc9-4081-837c-6e44298b03ca',
  '8fd1aabe-0fc9-4081-837c-6e44298b03ca',
  '8fd1aabe-0fc9-4081-837c-6e44298b03ca',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  '7b7eff7e-0382-4f4f-a60b-f6e9c63fb508',
  'be507312-77b8-4192-a2ee-ada36d8d9a47',
  '788a58e6-faf9-4329-9c7e-0d6d3b6bb778',
  'e473dd7b-425b-4d0e-add0-2e0b94b987b3'],
 '1199d75b-437d-46af-86c0-ecd2b96cc2fd': ['1f50e10a-909e-4aad-87ac-2e4ad69c4b78',
  '1c270e8f-15cc-4bed-af51-56c06398b164',
  'f8712c2e-b44e-4f46-b720-6bfceef0830b',
  '2561401f-b324-4abc-b305-5f36bf9378d6',
  'a051cb03-6c18-45fd-befb-0f540ab3e30f',
  'a051cb03-6c18-45fd-befb-0f540ab3e30f',
  'f8712c2e-b44e-4f46-b720-6bfceef0830b'],
 '90ceae31-531a-4534-91c9-1a24ff1c0308': ['d5ed6912-3978-4939-907a-ba7bc84a62ad',
  '55475a8b-364e-42f9-9637-d70f0e803c95',
  '31bb5d74-0b1d-4d22-bd1c-3387e4d02925',
  'efda917b-8df0-4a67-a23f-226ce2d4142d',
  '31db0f15-906f-4e4d-b2d1-0880775f4092',
  'f0c9c43d-c183-4759-a6ad-59d6d223a5b9'],
 '9cfd8cad-8059-4f7e-8e77-9630ffddb890': ['870afd59-9344-4da7-bc46-990968d5bcfa',
  '941306f1-ce4e-4bb1-aea2-6da90b1d653c',
  'd3285eb8-e726-4b4f-9d3c-ada2141f7dc5',
  'd00ed0ca-1623-4c75-991e-8f98c6fe56ab',
  '266fbad5-f5fb-40df-ba3e-f4cf0066d2d0',
  'b21943c4-e1f9-4fb1-80cb-702d08b91f46',
  '6e459258-0fdf-4be6-9d9a-f60e84c9d0af',
  'e3b2a072-1bfc-445f-a1e6-c2e44d9305ec',
  'cfc4c1ab-57e4-4fec-a759-90028b90b35c',
  'cfc4c1ab-57e4-4fec-a759-90028b90b35c',
  '266fbad5-f5fb-40df-ba3e-f4cf0066d2d0',
  'b21943c4-e1f9-4fb1-80cb-702d08b91f46',
  '941306f1-ce4e-4bb1-aea2-6da90b1d653c'],
 'd8ab7656-f658-4f7c-b6fd-88af9f091742': ['d16e3a2f-05a7-40be-855e-5b810b524b61',
  '1f2c44ee-051a-4dbf-bbef-bad76026db84',
  '699bfb4e-35a6-4719-8c6e-30f20c46dd55',
  'bab1893c-f936-4d07-bb9d-4ffd1556736b',
  'aca366aa-3e72-456d-ac50-11809f7ed76e',
  'e5bb3af1-9da0-4965-8cd0-f193b2b423ae',
  'b37730f6-6614-468f-8c53-cff0cf8d23e9']}

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(sess_uuids_matrix).transform(sess_uuids_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,047aa8f9-0d61-433b-8f59-f5f6f8daf6c3,09e54ba6-8322-4a86-afa8-a01dc89cb59b,0ed39147-fed9-4179-82c4-4ff84f92531f,10760847-7b34-4af7-b53e-1dc0562d21c0,1500fa23-b233-4ab6-9e42-9506f8d9a8f5,17ebd84f-9971-4643-8a31-7cc8cd1b82b6,1af6395b-05c0-49e9-a63d-31774b8cc443,1c270e8f-15cc-4bed-af51-56c06398b164,1d20892e-df9a-4816-949f-6416fa32a10a,1df72535-5045-4145-a395-90c20d2c7c11,...,efda917b-8df0-4a67-a23f-226ce2d4142d,f0c9c43d-c183-4759-a6ad-59d6d223a5b9,f278a7c1-0785-48d7-bf05-539b1f48cc0c,f629a009-4764-4dcf-9121-953912923945,f7358105-0eb0-474a-ba3e-6266aca8f90a,f8712c2e-b44e-4f46-b720-6bfceef0830b,f8d5daeb-62a8-4332-9b88-3da8f0052d77,f98db070-b1c2-4f1e-b019-c13361eeef96,fd70efc6-4bea-4488-9b48-259dedb17253,fdfea6b2-7629-4525-b94e-994d0e1b4c02
0,False,True,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
3,True,False,True,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.0905, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

        support                                           itemsets
0      0.090909             (fd70efc6-4bea-4488-9b48-259dedb17253)
1      0.090909             (f98db070-b1c2-4f1e-b019-c13361eeef96)
2      0.090909             (f278a7c1-0785-48d7-bf05-539b1f48cc0c)
3      0.090909             (c3f38f1d-a1be-477a-8692-9369ce7d2c44)
4      0.090909             (a32ff6ba-c480-4519-b91e-539517820571)
...         ...                                                ...
72592  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...
72593  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, e5bb3af...
72594  0.090909  (b37730f6-6614-468f-8c53-cff0cf8d23e9, e5bb3af...
72595  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...
72596  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...

[72597 rows x 2 columns]

In [5]:
frequent_itemsets["length"] = frequent_itemsets["itemsets"].apply(lambda x: len(x))
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

        support                                           itemsets  length
0      0.090909             (fd70efc6-4bea-4488-9b48-259dedb17253)       1
1      0.090909             (f98db070-b1c2-4f1e-b019-c13361eeef96)       1
2      0.090909             (f278a7c1-0785-48d7-bf05-539b1f48cc0c)       1
3      0.090909             (c3f38f1d-a1be-477a-8692-9369ce7d2c44)       1
4      0.090909             (a32ff6ba-c480-4519-b91e-539517820571)       1
...         ...                                                ...     ...
72592  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       6
72593  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, e5bb3af...       6
72594  0.090909  (b37730f6-6614-468f-8c53-cff0cf8d23e9, e5bb3af...       6
72595  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       6
72596  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       7

[72597 rows x 3 columns]

In [6]:
large_frequent_itemsets = frequent_itemsets[frequent_itemsets["length"] >= 3]
large_frequent_itemsets

        support                                           itemsets  length
105    0.090909  (fd70efc6-4bea-4488-9b48-259dedb17253, f98db07...       3
109    0.090909  (c3f38f1d-a1be-477a-8692-9369ce7d2c44, f98db07...       3
110    0.090909  (c3f38f1d-a1be-477a-8692-9369ce7d2c44, fd70efc...       3
111    0.090909  (c3f38f1d-a1be-477a-8692-9369ce7d2c44, fd70efc...       3
112    0.090909  (c3f38f1d-a1be-477a-8692-9369ce7d2c44, fd70efc...       4
...         ...                                                ...     ...
72592  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       6
72593  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, e5bb3af...       6
72594  0.090909  (b37730f6-6614-468f-8c53-cff0cf8d23e9, e5bb3af...       6
72595  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       6
72596  0.090909  (aca366aa-3e72-456d-ac50-11809f7ed76e, b37730f...       7

[72011 rows x 3 columns]

In [7]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_vps", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [8]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_sess_uuids (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            SESS_UUID            TEXT     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [9]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_sess_uuids (ID, SUPPORT, SESS_UUID)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    if idx == 1000:
        break
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")

Records created successfully

In [10]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_sess_uuids_large (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            SESS_UUID            TEXT     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [11]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_sess_uuids_large (ID, SUPPORT, SESS_UUID)
    VALUES (%s, %s, %s)
"""

for idx, row in large_frequent_itemsets.iterrows():
    if idx == 1000:
        break
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully