In [1]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.81...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 59950}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:33.297062,NaN
1,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.782025,NaN
2,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.872072,NaN
3,GET,/robots.txt,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38286}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.891330,NaN
4,GET,/sitemap.xml,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38288}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.893769,NaN

In [2]:
ports = []

for _, row in df.iterrows():
  ports.append(row["peer"]["port"])

ports

[59950,
 38278,
 38278,
 38286,
 38288,
 38288,
 38286,
 38278,
 38304,
 38316,
 38324,
 38328,
 38318,
 38332,
 38334,
 38376,
 38386,
 38418,
 38286,
 38426,
 38348,
 38360,
 38374,
 38392,
 38406,
 38420,
 38278,
 38316,
 38436,
 38304,
 38438,
 38288,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38304,
 38288,
 38438,
 38304,
 38436,
 38288,
 38438,
 38288,
 38436,
 38304,
 38438,
 38288,
 38436,
 38304,
 38438,
 38436,
 38304,
 38436,
 38304,
 38438,
 38436,
 38304,
 38438,
 38304,
 38438,
 38304,
 38438,
 38304,
 38438,
 38316,
 38304,
 38438,
 38316,
 38438,
 38304,
 38316,
 38438,
 38304,
 38316,
 38304,
 38438,
 38304,
 38438,
 38278,
 38420,
 38406,
 38392,
 38438,
 38304,
 38420,
 38278,
 38392,
 38406,
 38438,
 38420,
 38278,
 38374,
 38392,
 38304,
 38438,
 38406,
 38286,
 38360,
 38278,
 38420,
 38374,
 38392,
 38304,
 38348,
 38286,
 38406,
 38360,
 38438,
 38374,
 38392,
 38304,
 38438,
 38286,
 38348,
 38374,
 38392,
 38286,
 38348,
 38438,
 38374,
 38392,
 38406,
 38374,
 38278,
 38438,
 38316,
 38436,
 38288,
 38392,
 38360,
 38348,
 38420,
 38376,
 38304,
 38318,
 38328,
 58014,
 38332,
 58024,
 38334,
 58018,
 38324,
 38286,
 58032,
 58032,
 58032,
 58032,
 58032,
 38418,
 38418,
 38418,
 38418,
 38418,
 38324,
 58018,
 38324,
 38324,
 58018,
 38324,
 38324,
 58018,
 38386,
 38324,
 38324,
 58018,
 38324,
 58018,
 38324,
 58018,
 58018,
 38324,
 58018,
 58018,
 38324,
 38324,
 38324,
 38426,
 58032,
 58032,
 58032,
 58032,
 58032,
 38418,
 38418,
 38418,
 38418,
 38418,
 58018,
 58018,
 58018,
 58018,
 58018,
 58032,
 38418,
 38418,
 38418,
 38418,
 38418,
 58018,
 58018,
 58018,
 58018,
 58018,
 38418,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 38418,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 58032,
 38418,
 38418,
 38418,
 38418,
 38418,
 38418,
 38328,
 38328,
 38328,
 45776,
 58018,
 38324,
 58018,
 38324,
 58018,
 38324,
 58018,
 38334,
 58032,
 38324,
 58018,
 38334,
 58032,
 38418,
 38324,
 38332,
 58014,
 58024,
 38334,
 58032,
 38418,
 38328,
 58014,
 38332,
 58024,
 38334,
 58032,
 38418,
 38328,
 45786,
 38318,
 38376,
 45776,
 58014,
 38332,
 58024,
 38334,
 58032,
 38418,
 45786,
 38328,
 38318,
 38376,
 45776,
 58014,
 58024,
 38332,
 38328,
 45786,
 38418,
 38318,
 38376,
 45776,
 58014,
 58024,
 38332,
 45786,
 38318,
 38418,
 38376,
 58014,
 45786,
 38418,
 38376,
 45786,
 58018,
 58018,
 58018,
 58018,
 58018,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 58018,
 58018,
 58018,
 58018,
 58018,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 38334,
 58032,
 58018,
 58018,
 58018,
 58018,
 58018,
 38334,
 38334,
 38334,
 38334,
 38334,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 38334,
 58032,
 45786,
 58018,
 38334,
 38418,
 38376,
 58018,
 38334,
 38334,
 38334,
 38334,
 38334,
 38334,
 38334,
 58018,
 58018,
 38334,
 58018,
 38334,
 58018,
 38334,
 58018,
 38334,
 58018,
 38334,
 38376,
 58018,
 58018,
 38376,
 58018,
 38334,
 38376,
 38334,
 38376,
 38334,
 38376,
 38334,
 58018,
 38376,
 38334,
 38376,
 58018,
 38334,
 58018,
 38376,
 38334,
 38418,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 58018,
 ...]

In [3]:
ports_matrix = []
tmp = []

for i, x in enumerate(ports):
  if i % 10 == 0 and i != 0:
    ports_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  ports_matrix.append(tmp)

ports_matrix

[[59950, 38278, 38278, 38286, 38288, 38288, 38286, 38278, 38304, 38316],
 [38324, 38328, 38318, 38332, 38334, 38376, 38386, 38418, 38286, 38426],
 [38348, 38360, 38374, 38392, 38406, 38420, 38278, 38316, 38436, 38304],
 [38438, 38288, 38304, 38304, 38304, 38304, 38304, 38304, 38304, 38304],
 [38304, 38304, 38304, 38304, 38304, 38304, 38304, 38304, 38304, 38304],
 [38304, 38304, 38304, 38304, 38304, 38304, 38288, 38438, 38304, 38436],
 [38288, 38438, 38288, 38436, 38304, 38438, 38288, 38436, 38304, 38438],
 [38436, 38304, 38436, 38304, 38438, 38436, 38304, 38438, 38304, 38438],
 [38304, 38438, 38304, 38438, 38316, 38304, 38438, 38316, 38438, 38304],
 [38316, 38438, 38304, 38316, 38304, 38438, 38304, 38438, 38278, 38420],
 [38406, 38392, 38438, 38304, 38420, 38278, 38392, 38406, 38438, 38420],
 [38278, 38374, 38392, 38304, 38438, 38406, 38286, 38360, 38278, 38420],
 [38374, 38392, 38304, 38348, 38286, 38406, 38360, 38438, 38374, 38392],
 [38304, 38438, 38286, 38348, 38374, 38392, 38286, 38348, 38438, 38374],
 [38392, 38406, 38374, 38278, 38438, 38316, 38436, 38288, 38392, 38360],
 [38348, 38420, 38376, 38304, 38318, 38328, 58014, 38332, 58024, 38334],
 [58018, 38324, 38286, 58032, 58032, 58032, 58032, 58032, 38418, 38418],
 [38418, 38418, 38418, 38324, 58018, 38324, 38324, 58018, 38324, 38324],
 [58018, 38386, 38324, 38324, 58018, 38324, 58018, 38324, 58018, 58018],
 [38324, 58018, 58018, 38324, 38324, 38324, 38426, 58032, 58032, 58032],
 [58032, 58032, 38418, 38418, 38418, 38418, 38418, 58018, 58018, 58018],
 [58018, 58018, 58032, 38418, 38418, 38418, 38418, 38418, 58018, 58018],
 [58018, 58018, 58018, 38418, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58032, 38418, 58032, 38418, 58032],
 [38418, 38418, 58032, 38418, 58032, 38418, 58032, 38418, 58032, 38418],
 [58032, 38418, 58032, 38418, 58032, 38418, 38418, 38418, 38418, 38418],
 [38418, 38328, 38328, 38328, 45776, 58018, 38324, 58018, 38324, 58018],
 [38324, 58018, 38334, 58032, 38324, 58018, 38334, 58032, 38418, 38324],
 [38332, 58014, 58024, 38334, 58032, 38418, 38328, 58014, 38332, 58024],
 [38334, 58032, 38418, 38328, 45786, 38318, 38376, 45776, 58014, 38332],
 [58024, 38334, 58032, 38418, 45786, 38328, 38318, 38376, 45776, 58014],
 [58024, 38332, 38328, 45786, 38418, 38318, 38376, 45776, 58014, 58024],
 [38332, 45786, 38318, 38418, 38376, 58014, 45786, 38418, 38376, 45786],
 [58018, 58018, 58018, 58018, 58018, 38334, 58032, 38334, 58032, 38334],
 [58032, 38334, 58032, 38334, 58032, 58018, 58018, 58018, 58018, 58018],
 [38334, 58032, 38334, 58032, 38334, 58032, 38334, 58032, 38334, 58032],
 [58018, 58018, 58018, 58018, 58018, 38334, 38334, 38334, 38334, 38334],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 38334, 58032, 45786, 58018, 38334, 38418, 38376, 58018, 38334],
 [38334, 38334, 38334, 38334, 38334, 38334, 58018, 58018, 38334, 58018],
 [38334, 58018, 38334, 58018, 38334, 58018, 38334, 38376, 58018, 58018],
 [38376, 58018, 38334, 38376, 38334, 38376, 38334, 38376, 38334, 58018],
 [38376, 38334, 38376, 58018, 38334, 58018, 38376, 38334, 38418, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018, 58018],
 [58018, 58018, 38334, 45786, 58032, 38376, 58018, 38418, 45786, 38418],
 [58032, 58014, 38334, 38376, 58018, 45786, 38318, 58014, 38318, 58018],
 [38376, 45786, 58018, 38318, 38376, 58014, 38318, 38376, 58018, 58014],
 [38376, 38334, 45786, 38318, 38334, 38376, 45786, 38318, 58014, 38376],
 [38334, 45786, 58014, 58032, 38376, 38318, 38334, 38418, 58018, 58014],
 [45786, 58032, 45786, 58032, 58018, 58014, 38318, 38376, 38418, 38334],
 [58018, 58032, 38334, 58018, 38418, 38376, 58032, 38418, 58032, 38376],
 [58018, 58032, 38334, 38318, 38376, 38418, 38318, 58032, 38334, 58014],
 [58018, 38376, 58024, 45786, 38332, 38418, 38318, 58032, 58024, 38334],
 [58014, 38376, 58018, 45786, 38376, 58018, 45786, 38376, 58018, 38318],
 [38334, 45786, 58032, 38418, 58024, 58014, 58018, 38376, 38318, 38334],
 [38332, 45786, 58032, 38324, 45776, 38328, 58024, 58014, 38334, 38332],
 [38318, 45786, 38324, 38324, 45786, 38318, 38332, 45786, 38318, 38318],
 [38332, 38318, 38332, 38318, 38332, 38332, 38318, 38332, 38318, 38318],
 [38332, 38318, 38332, 38332, 38318, 38318, 38334, 38318, 38318, 38318],
 [38318, 38318, 58024, 58014, 38328, 38318, 45776, 38318, 38318, 38318],
 [58018, 38376, 58032, 38318, 38418, 38324, 38324, 38332, 45786, 38334],
 [38332, 38334, 45776, 58024, 58014, 38328, 58032, 58018, 38418, 38376],
 [38318, 38324, 38324, 38332, 38332, 38334, 38334, 38324, 38324, 38332],
 [38334, 38334, 38324, 38324, 38334, 38324, 38324, 38324, 38324, 38334],
 [38324, 38332, 38318, 38324, 38332, 38334, 38318, 38332, 38324, 38334],
 [38318, 38332, 38324, 38334, 38318, 38332, 38324, 38334, 38332, 38324],
 [38334, 38332, 38324, 38334, 38332, 38324, 38334, 38332, 38324, 38334],
 [38332, 38324, 38318, 38334, 38332, 38318, 38334, 38324, 38332, 38334],
 [38324, 38318, 38332, 38318, 38324, 38334, 38332, 38318, 38334, 38324],
 [38332, 38318, 38324, 38334, 38332, 38318, 58018, 38324, 38418, 38376],
 [58032, 38334, 38318, 58018, 38376, 38334, 58032, 38418, 38324, 58018],
 [38318, 58032, 38324, 38418, 38334, 38376, 58018, 38332, 38318, 58014],
 [38328, 58032, 38376, 58018, 38334, 38324, 38418, 38318, 38332, 38328],

In [4]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(ports_matrix).transform(ports_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,33486,33620,34102,34786,34798,34814,35368,35374,35386,35394,...,60012,60014,60026,60052,60070,60556,60566,60576,60592,60598
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1142,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1143,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1144,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1145,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.05, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(20)

     support               itemsets
0   0.171030                (38334)
1   0.151832                (38324)
2   0.144852                (38376)
3   0.142234                (38418)
4   0.119546                (38318)
5   0.116928                (38328)
6   0.114311                (38332)
7   0.114311                (58014)
8   0.278360                (58018)
9   0.147469                (58032)
10  0.114311                (45776)
11  0.096859                (45786)
12  0.050611                (51580)
13  0.128272                (56620)
14  0.083770         (58018, 38334)
15  0.112565         (38324, 38334)
16  0.064572         (58018, 38324)
17  0.053229  (58018, 38324, 38334)
18  0.096859         (38376, 38334)
19  0.074171         (38376, 38324)

In [10]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [11]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_ports (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            PORT            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [12]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_ports (ID, SUPPORT, PORT)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully