In [1]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.81...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 59950}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:33.297062,NaN
1,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.782025,NaN
2,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.872072,NaN
3,GET,/robots.txt,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38286}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.891330,NaN
4,GET,/sitemap.xml,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38288}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.893769,NaN

In [2]:
sess_uuids = []

for _, row in df.iterrows():
  sess_uuid = row.get("cookies", {}).get("sess_uuid") or row.get("response_msg", {}).get("response", {}).get("message", {}).get("sess_uuid")
  sess_uuids.append(sess_uuid)

sess_uuids

['123ab54e-70ac-4c74-a8d9-3404a3eba407',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 '844ef1b6-a5a8-4467-bca3-52888dff2967',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'cd704f30-7581-47a2-a046-0445fec47673',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
 'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',

In [3]:
sess_uuids_matrix = []
tmp = []

for i, x in enumerate(sess_uuids):
  if i % 10 == 0 and i != 0:
    sess_uuids_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  sess_uuids_matrix.append(tmp)

sess_uuids_matrix

[['123ab54e-70ac-4c74-a8d9-3404a3eba407',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967',
  'cd704f30-7581-47a2-a046-0445fec47673',
  '844ef1b6-a5a8-4467-bca3-52888dff2967'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'cd704f30-7581-47a2-a046-0445fec47673'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['cd704f30-7581-47a2-a046-0445fec47673',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644'],
 ['f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',
  'f9023d7d-bf0e-49cb-94dd-12f5aec7f644',

In [4]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(sess_uuids_matrix).transform(sess_uuids_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,0009bcdd-ab8d-4426-9159-fa6488e3b6e8,000b846a-829f-4ba4-ae0a-beef6551c61f,001c05d4-8faa-46a0-b6ee-44eba4dddcf4,00310dcb-1124-445c-87a8-1563bedf97cf,004e15c6-cb5a-46c4-a7e3-269afaa80c1a,005d1011-a990-4f13-9ccd-5fa3e1729d12,005ebc84-12d5-4c5a-abcd-836624603ca6,006437da-28b8-467f-a339-1d4c64d8e8a4,006d0b8d-5463-4c93-83a3-24a93b5a3f33,006e172a-5d3c-4c50-bf62-0c0550a8183a,...,ff0be5f7-d4d2-4589-87af-ad1a0945f2e8,ff36be32-294a-4a06-829a-e104b4d102ba,ff396814-b852-4f27-9dd4-726760be1ba8,ff3f27cf-0c97-47e2-8068-a4d602e568af,ff477011-2b95-40c6-aa79-23f3c90ae3f3,ff6139fb-5a86-46fd-b0dc-0aba06032890,ff74fdda-0467-47f4-9752-84877982017d,ffe83a18-4217-4cb0-b975-69fb0d4d0c3e,fff89e6b-eb28-4f1a-9e02-1319dcf35dc6,fffc5125-3d07-4d83-84f3-75ddd1052ec0
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1142,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1143,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1144,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1145,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.002, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

      support                                           itemsets
0    0.495637             (f9023d7d-bf0e-49cb-94dd-12f5aec7f644)
1    0.333333             (cd704f30-7581-47a2-a046-0445fec47673)
2    0.221640             (844ef1b6-a5a8-4467-bca3-52888dff2967)
3    0.002618             (9bad0897-835a-421c-9f0f-69d09afa5c2d)
4    0.002618             (ff477011-2b95-40c6-aa79-23f3c90ae3f3)
..        ...                                                ...
98   0.002618  (25b928e0-4e63-4cca-9722-c150d83cf159, dd5f838...
99   0.002618  (a085c012-e91f-460c-9afb-1faef060ab2e, dd5f838...
100  0.002618  (40195b93-a6e7-4885-87d8-ec1be8cc6719, a085c01...
101  0.002618  (40195b93-a6e7-4885-87d8-ec1be8cc6719, dd5f838...
102  0.002618  (40195b93-a6e7-4885-87d8-ec1be8cc6719, a085c01...

[103 rows x 2 columns]

In [14]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [15]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_sess_uuids (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            SESS_UUID            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [16]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_sess_uuids (ID, SUPPORT, SESS_UUID)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully