In [13]:
import pandas as pd

df = pd.read_json("../tanner_report.json", lines=True)

df.head(5)

,method,path,headers,uuid,peer,status,cookies,response_msg,timestamp,post_data
0,GET,/,"{'host': 'localhost', 'user-agent': 'curl/7.81...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 59950}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:33.297062,NaN
1,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.782025,NaN
2,GET,/,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38278}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.872072,NaN
3,GET,/robots.txt,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38286}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.891330,NaN
4,GET,/sitemap.xml,"{'host': '127.0.0.1', 'user-agent': 'Mozilla/5...",50d7b1f4-6ef6-4338-b372-dbd50f852dd9,"{'ip': '172.18.0.1', 'port': 38288}",200,{'sess_uuid': None},"{'version': '0.6.0', 'response': {'message': {...",2025-06-08 10:53:45.893769,NaN

In [4]:
ips = []

for _, row in df.iterrows():
  ips.append(row["peer"]["ip"])

ips

['172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 '172.18.0.1',
 ...]

In [5]:
ips_matrix = []
tmp = []

for i, x in enumerate(ips):
  if i % 10 == 0 and i != 0:
    ips_matrix.append(tmp)
    tmp = []
  tmp.append(x)

# Add the last group if not empty
if tmp:
  ips_matrix.append(tmp)

ips_matrix

[['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1',
  '172.18.0.1'],
 ['172.18.0.1',
  '172.18.0.1',

In [6]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(ips_matrix).transform(ips_matrix)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

      172.18.0.1
0           True
1           True
2           True
3           True
4           True
...          ...
1141        True
1142        True
1143        True
1144        True
1145        True

[1146 rows x 1 columns]

In [9]:
# frequent_itemsets = fpgrowth(df, min_support=0.3, use_colnames=True)
frequent_itemsets = fpgrowth(df, min_support=0.5, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets.head(20)

   support      itemsets
0      1.0  (172.18.0.1)

In [10]:
import psycopg2

conn = psycopg2.connect(database="web_honeypot_generated", user = "postgres", password = "admin", host = "127.0.0.1", port = "5432")

print("Opened database successfully")

Opened database successfully

In [11]:
# create table
cur = conn.cursor()
cur.execute('''CREATE TABLE assoc_rules_ips (
            ID INT PRIMARY KEY     NOT NULL,
            SUPPORT           REAL    NOT NULL,
            IP            VARCHAR(255)     NOT NULL);''')

print("Table created successfully")

conn.commit()

Table created successfully

In [12]:
# insert data

cur = conn.cursor()

insert_query = """
    INSERT INTO assoc_rules_ips (ID, SUPPORT, IP)
    VALUES (%s, %s, %s)
"""

for idx, row in frequent_itemsets.iterrows():
    cur.execute(
        insert_query,
        (int(idx), float(row["support"]), str(list(row["itemsets"])))
    )

conn.commit()
print("Records created successfully")
conn.close()

Records created successfully